version: 0.2

env:
  variables:
    ACCOUNT_ID: "069423017110"
    REGION: "ap-south-1"
    REPO: "swiggy"

phases:
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com

  build:
    commands:
      - cd DevOps-Project-23/Swiggy_clone
      - docker build -t $REPO:latest .
      - docker tag $REPO:latest $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/$REPO:latest
      - docker push $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/$REPO:latest

  post_build:
    commands:
      - echo "Docker image pushed successfully"

artifacts:
  files:
    - appspec.yaml
